name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  test-python:
    name: Run Tests (Python)
    runs-on: ubuntu-latest
    #needs: [security scan, code quality]

    defaults:
      run:
        working-directory: playwright-python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  test-typescript:
    name: Run Tests (TypeScript)
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality]  # Quality gates must pass first

    defaults:
      run:
        working-directory: playwright-typescript

    steps:
      - name: Checkout code
        uses: actions/checkout@v4






  test-login:
    name: Activity
    runs-on: ubuntu-latest
    environment: develop

#    defaults:
#      run:
#        working-directory: ci-training

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: playwright-typescript/package-lock.json

      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test successful login with valid credentials/scenarios.spec.ts

